[tasks.release-linux]
dependencies = ["clean_release_linux","pre_build_linux", "build_release_linux"]

[tasks.clean_release_linux]
script = ["rm -rf target/Spacewars.AppDir || exit 0"]

[tasks.pre_build_linux]
script = [
    "mkdir -p releases/linux || exit 0"
]

[tasks.build_release_linux]
dependencies = ["clean_release_linux"]
script_runner = "bash"
script = [
    "cargo build --release",
    "linuxdeploy-x86_64.AppImage --appdir target/Spacewars.AppDir -e target/release/spacewars",
    "mkdir -p target/Spacewars.AppDir",
    "cp -r resources target/Spacewars.AppDir/usr/bin",
    "linuxdeploy-x86_64.AppImage --appdir target/Spacewars.AppDir -e target/release/spacewars --desktop-file=resources/packaging/Spacewars.desktop --icon-file=resources/packaging/icon.png",
    "appimagetool-x86_64.AppImage target/Spacewars.AppDir",
    "mv Spacewars-x86_64.AppImage releases/linux",
]

[tasks.release-windows]
dependencies = ["clean_release_windows","pre_build_windows", "build_release_windows"]

[tasks.clean_release_windows]
script_runner = "cmd"
script = ['del /F /Q releases']


[tasks.pre_build_windows]
script_runner = "cmd"
script = [
    'mkdir releases\windows\spacewars || exit 0',
]

[tasks.build_release_windows]
script_runner = "cmd"
script = [
    #"cargo build --release",
    'copy target\release\spacewars.exe releases\windows\spaceswars\spaceswars.exe',
    'copy resources releases\windows\spaceswars',
    'copy *.txt releases\windows\spacewars',
    'copy *.md releases\windows\spacewars',
]
