[tasks.release]
dependencies = ["clean_release","pre_build", "build_release_linux"]

[tasks.pre_build]
script = [
    "mkdir -p releases/linux || exit 0"
]

[tasks.build_release_windows]
script = [
    "cargo build --release --target x86_64-pc-windows-gnu",
]

[tasks.build_release_linux]
dependencies = ["clean_release_linux"]
script_runner = "bash"
script = [
    "cargo build --release",
    "linuxdeploy-x86_64.AppImage --appdir target/Spacewars.AppDir -e target/release/spacewars",
    "mkdir -p target/Spacewars.AppDir",
    "cp -r resources target/Spacewars.AppDir",
    "linuxdeploy-x86_64.AppImage --appdir target/Spacewars.AppDir -e target/release/spacewars --desktop-file=resources/packaging/Spacewars.desktop --icon-file=resources/packaging/icon.png",
#    "appimagetool-x86_64.AppImage Spacewars.AppDir",
#    "mv Spacewars-x86_64.AppImage ../releases/linux",
]

[tasks.clean_release]
dependencies = ["clean_release_linux"]
script = ["rm -Rf releases/linux"]

[tasks.clean_release_linux]
script = ["rm -rf target/Spacewars.AppDir || exit 0"]

[tasks.clean]
dependencies = ["clean_release"]
